version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/openjdk:25.0'
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: mvn verify sonar:sonar
  integration-tests:
    executor: vm
    steps:
      - checkout
      - run:
          name: Install Kubectl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Install Istioctl
          command: |
            curl -L https://istio.io/downloadIstio | sh -
            cd istio-*
            chmod +x bin/istioctl
            sudo mv bin/istioctl /usr/local/bin/istioctl
      - run:
          name: Install Kind
          command: |
            [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
            chmod +x ./kind
            sudo mv ./kind /usr/local/bin/kind
      - run:
          name: Create Kind Cluster
          command: |
            kind create cluster --name c1
      - run:
          name: Install Istio
          command: |
            istioctl install --set profile=default -y
      - run:
          name: Run Tests
          command: |
            istioctl version
            mvn failsafe:integration-test
      - run:
          name: Delete Kind Cluster
          command: |
            kind delete cluster --name c1

executors:
  jdk:
    docker:
      - image: 'cimg/openjdk:25.0'
  vm:
    machine:
      image: ubuntu-2204:current
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

orbs:
  maven: circleci/maven@2.1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: jdk
      - build:
          context: SonarCloud
      - integration-tests:
          requires:
            - build
            - maven/test